version: "3.9"

services:
  backend:
    build: ./backend
    container_name: express_backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=my_database
      - DB_PORT=5432
    volumes:
      - ./backend:/usr/src/app
    command: npm run dev

  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    container_name: vite_app
    ports:
      - "8080:8080"
    volumes:
      - ./app:/usr/src/app

volumes:
  postgres_data:
