version: "3.9"

networks:
  gh_dashboard:

services:
  backend:
    build: ./backend
    container_name: express_backend
    networks:
      - gh_dashboard
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=my_database
      - DB_PORT=5432
    volumes:
      - ./backend:/usr/src/app
    command: npm run dev

  postgres:
    image: postgres:16
    container_name: postgres_db
    networks:
      - gh_dashboard
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: ./app
    container_name: vite_app
    networks:
      - gh_dashboard
    ports:
      - "5173:5173"
    volumes:
      - ./app:/usr/src/app
    command: npm run dev

volumes:
  postgres_data:
