version: "3.9"

services:
  backend:
    build: ./backend
    container_name: express_backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=my_database
      - DB_PORT=5432
      - GITHUB_CLIENT_ID=Ov23liqag9cwD6CjBQRt
      - GITHUB_CLIENT_SECRET=0c766a5a6f7db5cf65e505de3fd26896ab1ee1c1
      - SYNC_INTERVAL=3600000
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules # Preserve container's node_modules
    command: npm run start

  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    container_name: vite_app
    ports:
      - "8080:8080"
    environment:
      - VITE_APP_GITHUB_CLIENT_ID=Ov23liqag9cwD6CjBQRt
      - VITE_APP_BACKEND_URL=http://localhost:3000
    volumes:
      - ./app:/usr/src/app

volumes:
  postgres_data:
